-- Create the table
create table notes (
  id bigint generated by default as identity primary key,
  type text not null default 'text', -- 'text' or 'image'
  content text, -- Text content or Base64 image
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For simplicity in this demo, we'll enable public access.
-- In production, you should restrict this to authenticated users.
alter table notes enable row level security;

create policy "Enable read access for all users"
on notes for select
using (true);

create policy "Enable insert access for all users"
on notes for insert
with check (true);

create policy "Enable update access for all users"
on notes for update
using (true);

create policy "Enable delete access for all users"
on notes for delete
using (true);
